version: 2.1
orbs:
    sonarcloud: sonarsource/sonarcloud@1.0.1
jobs:
    build-and-test:
        docker:
            - image: circleci/node:12.16
        steps:
            - checkout
            - run:
                  name: update-npm
                  command: 'sudo npm install -g npm@5'
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run: npm run lint
            - run:
                  name: test
                  command: npx jest --collectCoverage=true
            - store_artifacts:
                  path: coverage
            - sonarcloud/scan

workflows:
    build-and-test:
        jobs:
            - build-and-test:
                  context: SonarCloud
