version: 2.1
orbs:
    node: circleci/node@2.0.3
jobs:
    build-and-test:
        executor:
            name: node/default
        steps:
            - checkout
            - run:
				name: update-npm
				command: 'sudo npm install -g npm@5'
			- restore_cache:
				key: dependency-cache-{{ checksum "package-lock.json" }}
			- run: npm install
			- save_cache:
				key: dependency-cache-{{ checksum "package-lock.json" }}
				paths:
					- ./node_modules
			- run: npm run lint
			- run:
				name: test
				command: npm run test --coverage
			- store_artifacts:
				path: coverage
				prefix: coverage
					
workflows:
    build-and-test:
        jobs:
            - build-and-test
