version: 2.1
orbs:
    sonarcloud: sonarsource/sonarcloud@1.0.1
jobs:
    build-and-test:
        docker:
            - image: circleci/node:12.16
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run: npm run lint -- --format junit -o reports/junit/js-lint-results.xml
            - run:
                  name: test
                  environment:
                      JEST_JUNIT_OUTPUT_DIR: 'reports/junit/js-test-results.xml'
                  command: npm run test --ci --runInBand --reporters=default --reporters=jest-junit
            - store_test_results:
                  path: reports
            - store_artifacts:
                  path: reports
            - sonarcloud/scan

workflows:
    build-and-test:
        jobs:
            - build-and-test:
                  context: SonarCloud
